version: "3"

networks:
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryption.
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  phpfpm:
    build: ./.docker/phpfpm
    networks:
      - app
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAIL=1 # Uncomment to enable mailhog.
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - COMPOSER_VERSION=2
    depends_on:
      - mariadb
      - memcached
    volumes:
      - .:/app:delegated
      - drush-cache:/root/.drush

  nginx:
    image: nginx:latest
    networks:
      - app
    depends_on:
      - phpfpm
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated

  memcached:
    image: 'memcached:latest'
    networks:
      - app
    ports:
      - '11211'
    environment:
      - MEMCACHED_CACHE_SIZE=64

  mailhog:
    image: mailhog/mailhog
    networks:
      - app
    ports:
      - "1025"
      - "8025"

  node:
    image: node:14
    volumes:
      - .:/app:delegated

# Drush cache volume to persist cache between runs.
volumes:
  drush-cache:
