# itk-version: 1.0.0
version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryption.
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  phpfpm:
    build: ./.docker/development/phpfpm
    networks:
      - app
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAIL=1 # Uncomment to enable mailhog.
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - COMPOSER_VERSION=2
    extra_hosts:
      # Used by ssh tunnel to Azure SQL Server
      #
      # Run these commands to make it actually work:
      #
      # $ # Copy ssh keys to container
      # $ docker-compose exec phpfpm mkdir -p /root/.ssh
      # $ docker-compose cp ~/.ssh/id_rsa phpfpm:/root/.ssh/id_rsa
      # $ docker-compose cp ~/.ssh/id_rsa-cert.pub phpfpm:/root/.ssh/id_rsa-cert.pub
      # $ # Create ssh tunnel using IPv4 (`-4`)
      # $ docker-compose exec phpfpm ssh -4 -f deploy@dp-lager.aarhuskommune.dk -L 1433:aadsrvb2c.database.windows.net:1433 -N
      - "aadsrvb2c.database.windows.net:127.0.0.1"
    depends_on:
      - mariadb
      - memcached
    volumes:
      - .:/app:delegated

  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  memcached:
    image: 'memcached:latest'
    networks:
      - app
    ports:
      - '11211'
    environment:
      - MEMCACHED_CACHE_SIZE=64

  mailhog:
    image: mailhog/mailhog
    networks:
      - app
    ports:
      - "1025"
      - "8025"

  node:
    image: node:14
    volumes:
      - .:/app:delegated
