<?php

/**
 * @file
 * Hooks related to the user entity.
 */

use Drupal\dagplejelager_user\Helper\DaycareUserHelper;

/**
 * Implements hook_user_local_tasks_alter().
 *
 * @see \Drupal\dagplejelager_user\Helper\DaycareUserHelper::localTasksAlter()
 *
 * @phpstan-param array<string, mixed> $local_tasks
 */
function dagplejelager_user_local_tasks_alter(&$local_tasks): void {
  Drupal::service(DaycareUserHelper::class)->localTasksAlter($local_tasks);
}
