#!/usr/bin/env bash

if ! composer coding-standards-check; then
  cat >&2 << EOF
Please fix any coding standards issues before commit'ing!
EOF
  exit 1
fi

if ! yarn coding-standards-check; then
  cat >&2 << EOF
Please fix any coding standards issues before commit'ing!
EOF
  exit 1
fi

cat >&2 << EOF
Have your changes been added to CHANGELOG.md ? Should they ?
EOF

exit 0

