#!/usr/bin/env bash

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

if ! composer coding-standards-check; then
  cat >&2 << EOF
Please fix any coding standards issues before commit'ing!
EOF
  exit 1
fi

if ! yarn coding-standards-check; then
  cat >&2 << EOF
Please fix any coding standards issues before commit'ing!
EOF
  exit 1
fi

echo -e "${yellow}Git hook was SUCCESSFUL!${no_color}\n"

exit 0

